const BASE_STYLES = `
  :root{color-scheme:dark;--ink:#f7f7fb;--muted:#a7a4b4;--panel:#17151f;--line:#2c2937;--violet:#9d7cff;--mint:#68e0b4;--bg:#0d0c12}
  *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 5%,#241d3f 0,transparent 34%),var(--bg);color:var(--ink);font:15px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100vh}
  button,input,textarea{font:inherit}button{cursor:pointer}.brand{display:flex;align-items:center;gap:11px;font-weight:820;letter-spacing:-.02em}.brand-mark{width:35px;height:35px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,var(--violet),#6d47ef);box-shadow:0 10px 30px #8b68ff40}.eyebrow{text-transform:uppercase;letter-spacing:.14em;color:var(--mint);font-weight:800;font-size:11px}.muted{color:var(--muted)}
  .button{border:0;border-radius:12px;padding:11px 16px;background:var(--violet);color:#0d0c12;font-weight:800;transition:transform .15s,filter .15s}.button:hover{filter:brightness(1.08)}.button:active{transform:translateY(1px)}.button.secondary{background:#24212e;color:var(--ink);border:1px solid var(--line)}.button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #9d7cff55;outline-offset:2px}
`;

export function loginPage(nonce) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>FitJo Admin · Secure access</title>
<style nonce="${nonce}">${BASE_STYLES}
  main{min-height:100vh;display:grid;place-items:center;padding:28px}.login{width:min(100%,430px);background:#17151feb;border:1px solid var(--line);border-radius:24px;padding:30px;box-shadow:0 30px 90px #0008;backdrop-filter:blur(16px)}h1{font-size:30px;letter-spacing:-.04em;margin:25px 0 5px}.sub{color:var(--muted);margin:0 0 25px}.field{margin:16px 0}.field label{display:block;font-weight:750;margin-bottom:7px}.field input{width:100%;border:1px solid var(--line);border-radius:12px;background:#0f0e15;color:var(--ink);padding:13px 14px}.code{letter-spacing:.28em;font-variant-numeric:tabular-nums}.login .button{width:100%;margin-top:8px}.error{min-height:24px;color:#ff9ba6;font-weight:650;margin-top:13px}.security{display:flex;gap:9px;margin-top:20px;padding-top:18px;border-top:1px solid var(--line);color:var(--muted);font-size:13px}.security span{color:var(--mint)}
</style></head><body><main><section class="login" aria-labelledby="title">
  <div class="brand"><span class="brand-mark">FJ</span><span>FitJo Admin</span></div>
  <div class="eyebrow" style="margin-top:24px">Restricted area</div><h1 id="title">Verify it’s you</h1>
  <p class="sub">Enter the admin password and the current six-digit code from your authenticator app.</p>
  <form id="loginForm"><div class="field"><label for="password">Admin password</label><input id="password" name="password" type="password" autocomplete="current-password" required autofocus></div>
  <div class="field"><label for="code">Authenticator code</label><input class="code" id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" placeholder="000000" required></div>
  <button class="button" id="submit" type="submit">Open admin dashboard</button><div class="error" id="error" role="alert" aria-live="polite"></div></form>
  <div class="security"><span>●</span><div>Both checks are verified securely. Your session ends automatically after 8 hours.</div></div>
</section></main><script nonce="${nonce}">
  const form=document.getElementById("loginForm"),error=document.getElementById("error"),submit=document.getElementById("submit");
  form.addEventListener("submit",async(event)=>{event.preventDefault();error.textContent="";submit.disabled=true;submit.textContent="Checking…";
    try{const response=await fetch("/admin/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"login",password:form.password.value,code:form.code.value})});
      if(response.ok){location.replace("/admin");return}const data=await response.json().catch(()=>({}));error.textContent=response.status===429?"Too many attempts. Wait one minute and try again.":data.error||"Could not sign in. Try again.";form.code.select();
    }catch{error.textContent="Could not reach the secure sign-in service."}finally{submit.disabled=false;submit.textContent="Open admin dashboard"}});
</script></body></html>`;
}

export function setupPage(nonce) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>FitJo Admin · Setup required</title><style nonce="${nonce}">${BASE_STYLES}main{min-height:100vh;display:grid;place-items:center;padding:28px}.card{max-width:560px;background:var(--panel);border:1px solid var(--line);padding:30px;border-radius:24px}h1{font-size:30px;letter-spacing:-.04em;margin:22px 0 8px}p{color:var(--muted)}code{color:var(--mint)}</style></head><body><main><section class="card"><div class="brand"><span class="brand-mark">FJ</span><span>FitJo Admin</span></div><div class="eyebrow" style="margin-top:22px">One-time setup</div><h1>Admin access isn’t configured</h1><p>Generate the three private admin values with <code>scripts/configure-admin.mjs</code>, add them to the site’s secure function environment, then redeploy.</p></section></main></body></html>`;
}

export function dashboardPage(nonce) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>FitJo Admin · Dashboard</title>
<style nonce="${nonce}">${BASE_STYLES}
  .shell{width:min(1180px,calc(100% - 36px));margin:auto}.topbar{height:82px;display:flex;align-items:center;border-bottom:1px solid var(--line)}.topbar .shell{display:flex;align-items:center;gap:16px}.topbar-actions{margin-left:auto;display:flex;gap:10px}.topbar a{text-decoration:none}.hero{padding:48px 0 25px}.hero h1{font-size:clamp(34px,5vw,58px);line-height:1;letter-spacing:-.055em;margin:7px 0 14px}.hero p{max-width:620px;color:var(--muted);font-size:17px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px;padding-bottom:50px}.card{background:linear-gradient(145deg,#191721,#13121a);border:1px solid var(--line);border-radius:20px;padding:21px}.stat{grid-column:span 3;min-height:142px;display:flex;flex-direction:column;justify-content:space-between}.stat-value{font-size:37px;line-height:1;font-weight:850;letter-spacing:-.05em}.stat-label,.tiny{color:var(--muted);font-size:13px}.members{grid-column:span 8}.actions{grid-column:span 4}.card h2{font-size:18px;margin:0 0 17px}.role-bars{display:grid;gap:9px}.role-row{display:grid;grid-template-columns:70px 1fr 28px;align-items:center;gap:10px;font-size:13px}.bar{height:8px;border-radius:99px;background:#272430;overflow:hidden}.bar span{display:block;height:100%;background:linear-gradient(90deg,var(--violet),var(--mint));border-radius:inherit}.user-list{display:grid;gap:9px}.user{display:flex;align-items:center;gap:12px;padding:11px;border:1px solid var(--line);border-radius:14px}.avatar{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:#2a2540;color:#cbbdff;font-weight:800}.user-copy{min-width:0;flex:1}.user-name{font-weight:760;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.user-meta{font-size:12px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pill{border-radius:999px;padding:3px 8px;background:#24212e;color:#c7c2d0;font-size:11px}.pill.off{background:#351c25;color:#ff9ba6}.icon-action{border:1px solid var(--line);background:#24212e;color:var(--ink);border-radius:10px;padding:7px 10px;font-size:12px;font-weight:750}.stack{display:grid;gap:17px}.action-block{padding-bottom:17px;border-bottom:1px solid var(--line)}.action-block:last-child{padding:0;border:0}.action-block label{display:block;font-weight:750;margin-bottom:7px}.action-block textarea{width:100%;min-height:85px;resize:vertical;background:#0f0e15;color:var(--ink);border:1px solid var(--line);border-radius:12px;padding:12px;margin-bottom:9px}.result{min-height:22px;color:var(--mint);font-weight:700;font-size:13px;margin-top:8px}.empty{color:var(--muted);padding:20px 0}.secure-dot{color:var(--mint)}
  .icon-action.danger{border-color:#4a2430;background:#2b1620;color:#ff9ba6}.pill.on{background:#173327;color:#8ff0c8}.action-block input{width:100%;background:#0f0e15;color:var(--ink);border:1px solid var(--line);border-radius:12px;padding:12px;margin-bottom:9px}
  .keys{grid-column:span 12}.key-controls{display:flex;gap:10px;margin:0 0 14px}.key-controls select{flex:1;background:#0f0e15;color:var(--ink);border:1px solid var(--line);border-radius:12px;padding:11px 12px}.key-list{display:grid;gap:9px}.key-row{display:flex;align-items:center;gap:12px;padding:11px;border:1px solid var(--line);border-radius:14px;flex-wrap:wrap}.key-copy{min-width:0;flex:1}.key-code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-weight:750;letter-spacing:.05em;white-space:nowrap}
  @media(max-width:850px){.stat{grid-column:span 6}.members,.actions{grid-column:1/-1}}@media(max-width:540px){.shell{width:min(100% - 24px,1180px)}.topbar{height:auto;padding:14px 0}.brand small{display:none}.topbar-actions .return{display:none}.hero{padding-top:34px}.stat{grid-column:1/-1;min-height:115px}.user{align-items:flex-start;flex-wrap:wrap}.user-copy{width:calc(100% - 50px)}}
</style></head><body>
<header class="topbar"><div class="shell"><div class="brand"><span class="brand-mark">FJ</span><span>FitJo <small class="muted">/ Admin</small></span></div><div class="topbar-actions"><a class="button secondary return" href="/">View public app</a><button class="button secondary" id="logout">Sign out</button></div></div></header>
<main class="shell"><section class="hero"><div class="eyebrow"><span class="secure-dot">●</span> Secure admin session</div><h1>Platform overview</h1><p>A separate control room for FitJo. Account information shown here belongs to this browser-based prototype.</p></section>
<section class="grid" aria-label="Admin overview">
  <article class="card stat"><div class="stat-label">Total accounts</div><div><div class="stat-value" id="totalUsers">0</div><div class="tiny">Saved in this browser</div></div></article>
  <article class="card stat"><div class="stat-label">Active accounts</div><div><div class="stat-value" id="activeUsers">0</div><div class="tiny">Not suspended</div></div></article>
  <article class="card stat"><div class="stat-label">Gyms listed</div><div><div class="stat-value">8</div><div class="tiny">Amman directory</div></div></article>
  <article class="card stat"><div class="stat-label">Announcements</div><div><div class="stat-value" id="announcementCount">0</div><div class="tiny">Sent from this browser</div></div></article>
  <article class="card members"><h2>Account access</h2><div class="role-bars" id="roleBars"></div><div style="height:18px"></div><div class="user-list" id="userList"></div></article>
  <aside class="card actions"><h2>Admin actions</h2><div class="stack">
    <div class="action-block"><label>Add member</label><div class="tiny" style="margin-bottom:9px">Create a member account and share the email and temporary password with them.</div><input id="newName" type="text" placeholder="Full name" autocomplete="off"><input id="newEmail" type="email" placeholder="member@email.com" autocomplete="off"><input id="newPw" type="text" placeholder="Temporary password (6+ characters)" autocomplete="off"><button class="button" id="addMember">Add member</button><div class="result" id="addResult" role="status"></div></div>
    <div class="action-block"><label for="broadcast">Broadcast announcement</label><textarea id="broadcast" placeholder="Write an update for FitJo members…"></textarea><button class="button" id="sendBroadcast">Send announcement</button><div class="result" id="broadcastResult" role="status"></div></div>
    <div class="action-block"><label>Member giveaway</label><div class="tiny">Randomly select an active member account.</div><button class="button secondary" id="giveaway" style="margin-top:10px">Pick a winner</button><div class="result" id="giveawayResult" role="status"></div></div>
  </div></aside>
  <article class="card keys"><h2>Access keys for coaches &amp; gym owners</h2>
    <div class="tiny" style="margin:-8px 0 14px">Generate a one-time key and send it to the coach or gym owner. They enter it when creating their account — without a key, those account types can’t sign up.</div>
    <div class="key-controls"><select id="keyRole" aria-label="Key type"><option value="coach">🧑‍🏫 Coach key</option><option value="owner">🏢 Gym owner key</option></select><button class="button" id="generateKey">Generate key</button></div>
    <div class="result" id="keyResult" role="status"></div>
    <div class="key-list" id="keyList"></div>
  </article>
</section></main>
<script nonce="${nonce}">
  const byId=(id)=>document.getElementById(id);
  const readArray=(key)=>{try{const value=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(value)?value:[]}catch{return[]}};
  const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
  const initials=(name)=>String(name||"?").trim().split(/\\s+/).slice(0,2).map((part)=>part[0]||"").join("").toUpperCase()||"?";
  const roles=["user","coach","staff","owner"],roleNames={user:"Members",coach:"Coaches",staff:"Gym staff",owner:"Gym owners"};let users=[];
  function render(){users=readArray("fj_users").filter((user)=>user&&typeof user==="object"&&user.role!=="admin");const active=users.filter((user)=>!user.banned);const announcements=readArray("fj_admin_broadcasts");
    byId("totalUsers").textContent=users.length;byId("activeUsers").textContent=active.length;byId("announcementCount").textContent=announcements.length;
    const maximum=Math.max(1,...roles.map((role)=>users.filter((user)=>(user.role||"user")===role).length));
    byId("roleBars").innerHTML=roles.map((role)=>{const count=users.filter((user)=>(user.role||"user")===role).length;return '<div class="role-row"><span>'+roleNames[role]+'</span><div class="bar"><span style="width:'+Math.round(count/maximum*100)+'%"></span></div><b>'+count+'</b></div>'}).join("");
    byId("userList").innerHTML=users.length?users.slice().reverse().map((user)=>{const role=roleNames[user.role||"user"]||"Member";const email=escapeHtml(user.email||"");return '<div class="user"><div class="avatar">'+escapeHtml(initials(user.name))+'</div><div class="user-copy"><div class="user-name">'+escapeHtml(user.name||"Unnamed account")+'</div><div class="user-meta">'+escapeHtml(user.email||"No email")+' · '+escapeHtml(role)+'</div></div><span class="pill '+(user.banned?'off':'')+'">'+(user.banned?'Suspended':'Active')+'</span><button class="icon-action" data-act="toggle" data-email="'+email+'">'+(user.banned?'Restore':'Suspend')+'</button><button class="icon-action danger" data-act="remove" data-email="'+email+'">Remove</button></div>'}).join(""):'<div class="empty">No prototype accounts have been created in this browser yet.</div>';
    const keys=readArray("fj_access_keys").filter((key)=>key&&typeof key==="object"&&key.key);
    byId("keyList").innerHTML=keys.length?keys.slice().reverse().map((key)=>{const roleName=key.role==="owner"?"Gym owner":"Coach";const status=key.revoked?'<span class="pill off">Revoked</span>':key.usedBy?'<span class="pill">Used · '+escapeHtml(key.usedBy)+'</span>':'<span class="pill on">Available</span>';const actions=(key.usedBy||key.revoked)?'<button class="icon-action danger" data-key-act="delete" data-key="'+escapeHtml(key.key)+'">Delete</button>':'<button class="icon-action" data-key-act="copy" data-key="'+escapeHtml(key.key)+'">Copy</button><button class="icon-action danger" data-key-act="revoke" data-key="'+escapeHtml(key.key)+'">Revoke</button>';return '<div class="key-row"><div class="key-copy"><div class="key-code">'+escapeHtml(key.key)+'</div><div class="user-meta">'+roleName+' · created '+new Date(key.createdAt||Date.now()).toLocaleDateString()+'</div></div>'+status+actions+'</div>'}).join(""):'<div class="empty">No access keys yet. Generate one above and send it to your coach or gym owner.</div>';
  }
  byId("userList").addEventListener("click",(event)=>{const button=event.target.closest("[data-act]");if(!button)return;const all=readArray("fj_users");const index=all.findIndex((user)=>user&&user.email===button.dataset.email);if(index<0)return;
    if(button.dataset.act==="remove"){const label=all[index].name||all[index].email||"this account";if(!confirm("Remove "+label+"? This permanently deletes the account."))return;all.splice(index,1)}else{all[index].banned=!all[index].banned}
    localStorage.setItem("fj_users",JSON.stringify(all));render()});
  byId("addMember").addEventListener("click",()=>{const name=byId("newName").value.trim();const email=byId("newEmail").value.trim().toLowerCase();const password=byId("newPw").value;const result=byId("addResult");
    if(!name||!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)){result.textContent="Enter a name and a valid email.";return}
    if(password.length<6){result.textContent="The temporary password needs at least 6 characters.";return}
    const all=readArray("fj_users");if(all.some((user)=>user&&user.email===email)){result.textContent="An account with that email already exists.";return}
    all.push({id:"u"+Date.now(),name,email,pw:btoa(unescape(encodeURIComponent(password))),age:18,gender:"na",goal:"fit",city:"",createdAt:Date.now(),role:"user",gymId:null,verified:true,banned:false,twoFA:false,twoFASecret:null,recovery:[],passkeys:0,provider:"admin",privacy:{profilePublic:true,showFav:false,trainerContact:true,shareData:true},notif:{offers:true,expiry:true,classes:true,news:false},intake:null,weights:[],reminders:{gym:{on:false,time:"19:00"},rest:{on:false,time:"10:00"}}});
    localStorage.setItem("fj_users",JSON.stringify(all));byId("newName").value="";byId("newEmail").value="";byId("newPw").value="";result.textContent="Member added: "+email;render()});
  const keyChunk=(length)=>{const alphabet="ABCDEFGHJKMNPQRSTUVWXYZ23456789";const bytes=new Uint8Array(length);crypto.getRandomValues(bytes);let out="";for(const byte of bytes)out+=alphabet[byte%alphabet.length];return out};
  byId("generateKey").addEventListener("click",()=>{const role=byId("keyRole").value==="owner"?"owner":"coach";const key="FJ-"+role.toUpperCase()+"-"+keyChunk(5)+"-"+keyChunk(5);const keys=readArray("fj_access_keys");keys.push({key,role,createdAt:Date.now(),usedBy:null,usedAt:null,revoked:false});localStorage.setItem("fj_access_keys",JSON.stringify(keys));byId("keyResult").textContent="New "+(role==="owner"?"gym owner":"coach")+" key: "+key;render()});
  byId("keyList").addEventListener("click",async(event)=>{const button=event.target.closest("[data-key-act]");if(!button)return;const keys=readArray("fj_access_keys");const index=keys.findIndex((key)=>key&&key.key===button.dataset.key);if(index<0)return;const act=button.dataset.keyAct;
    if(act==="copy"){try{await navigator.clipboard.writeText(keys[index].key);byId("keyResult").textContent="Key copied: "+keys[index].key}catch{byId("keyResult").textContent="Copy this key: "+keys[index].key}return}
    if(act==="revoke"){keys[index].revoked=true}else if(act==="delete"){keys.splice(index,1)}
    localStorage.setItem("fj_access_keys",JSON.stringify(keys));render()});
  byId("sendBroadcast").addEventListener("click",()=>{const message=byId("broadcast").value.trim();if(!message){byId("broadcastResult").textContent="Write an announcement first.";return}const items=readArray("fj_admin_broadcasts");items.push({message,createdAt:Date.now()});localStorage.setItem("fj_admin_broadcasts",JSON.stringify(items));byId("broadcast").value="";byId("broadcastResult").textContent="Announcement saved for "+users.length+" accounts.";render()});
  byId("giveaway").addEventListener("click",()=>{const pool=users.filter((user)=>!user.banned&&(user.role||"user")==="user");byId("giveawayResult").textContent=pool.length?"Winner: "+(pool[Math.floor(Math.random()*pool.length)].name||"Member"):"No active members are available."});
  byId("logout").addEventListener("click",async()=>{await fetch("/admin/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})}).catch(()=>{});location.replace("/admin")});render();
</script></body></html>`;
}
